# Generated by Django 2.1.5 on 2019-06-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckinfo',
            name='Truck_capacity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='truckinfo',
            name='Truck_length',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='truckinfo',
            name='Truck_width',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=20),
        ),
    ]
