# Generated by Django 2.1.5 on 2019-06-29 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190629_1021'),
        ('merchant', '0002_auto_20190629_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='permitted_states',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='services_provided',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField()),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.items')),
            ],
        ),
    ]
