# Generated by Django 2.2.1 on 2019-06-25 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_auto_20190625_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.user_info'),
        ),
    ]
