# Generated by Django 2.2.1 on 2019-06-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='merchantOrUser',
        ),
        migrations.AddField(
            model_name='user_info',
            name='merchant',
            field=models.BooleanField(default=False),
        ),
    ]
