# Generated by Django 2.1.5 on 2019-06-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
