# Generated by Django 2.2.2 on 2019-06-27 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_bets',
            name='merchant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_id', to='user_auth.user_info'),
        ),
    ]
