# Generated by Django 2.1.5 on 2019-06-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20190619_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timeToLive',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
