# Generated by Django 2.1.5 on 2019-06-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('item_weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item_length', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item_width', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item_height', models.DecimalField(decimal_places=2, max_digits=20)),
                ('handle_with_care', models.BooleanField(default=False)),
                ('item_material', models.CharField(max_length=100)),
                ('item_approximate_cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=20)),
                ('merchant_id', models.CharField(max_length=20)),
                ('comfirmed', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('final_price', models.IntegerField(default=0)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order_bets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('merchant_id', models.CharField(max_length=20)),
                ('bet_price', models.IntegerField()),
                ('extra_info', models.TextField()),
                ('date_of_bet', models.DateField(null=True)),
                ('pickup_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order_path_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('source_area', models.TextField()),
                ('source_city', models.CharField(max_length=30)),
                ('source_state', models.CharField(max_length=30)),
                ('source_pin', models.IntegerField()),
                ('destination_area', models.TextField()),
                ('destination_city', models.CharField(max_length=30)),
                ('destination_state', models.CharField(max_length=30)),
                ('destination_pin', models.IntegerField()),
                ('expecting_arrival', models.DateField(auto_now=True)),
            ],
        ),
    ]
