# Generated by Django 2.1.5 on 2019-06-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_info',
            name='item_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
