# Generated by Django 2.2 on 2019-06-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_by_customer',
            name='image',
            field=models.ImageField(blank=True, upload_to='item_image/'),
        ),
    ]
