# Generated by Django 2.1.5 on 2019-06-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_path_info',
            name='destination_pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_path_info',
            name='source_pin',
            field=models.IntegerField(),
        ),
    ]
