# Generated by Django 2.2.1 on 2019-06-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='item_id',
        ),
    ]
