# Generated by Django 2.1.5 on 2019-06-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_item_info_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
