# Generated by Django 2.2.1 on 2019-06-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20190615_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_bets',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order_bets',
            name='order_id',
            field=models.ManyToManyField(to='customer.order'),
        ),
    ]
