# Generated by Django 2.1.5 on 2019-06-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_order_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_info',
            name='auction_life',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
