# Generated by Django 2.1.5 on 2019-06-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_item_info_auction_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_path_info',
            name='destination_area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order_path_info',
            name='source_area',
            field=models.CharField(max_length=100),
        ),
    ]
