# Generated by Django 2.2 on 2019-06-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20190615_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images_by_customer',
            name='item_info',
        ),
        migrations.AddField(
            model_name='images_by_customer',
            name='item_info',
            field=models.ManyToManyField(to='customer.item_info'),
        ),
    ]
