# Generated by Django 2.1.5 on 2019-06-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20190619_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='merchant_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
