# Generated by Django 2.2 on 2019-06-15 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20190615_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_bets',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order_bets',
            name='order_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.order'),
            preserve_default=False,
        ),
    ]
