# Generated by Django 2.2.1 on 2019-06-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images_by_customer',
            old_name='item_info',
            new_name='item_information',
        ),
    ]
