# Generated by Django 2.2.1 on 2019-06-15 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20190615_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images_by_customer',
            name='item_information',
        ),
        migrations.AddField(
            model_name='images_by_customer',
            name='item_information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.item_info'),
            preserve_default=False,
        ),
    ]
