# Generated by Django 2.2.1 on 2019-06-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=40)),
                ('CompanyGST', models.CharField(max_length=50)),
                ('Location', models.TextField(verbose_name="Company's base location")),
                ('Owner', models.CharField(max_length=255)),
                ('PhoneNo', models.IntegerField(verbose_name='Company Phone No')),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TruckInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TruckName', models.CharField(max_length=255)),
                ('TruckId', models.CharField(max_length=10, verbose_name='Number Plate of Truck')),
                ('PermitType', models.CharField(max_length=25)),
                ('PermitDate', models.DateField(verbose_name='Till when is the permit valid')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.Company')),
            ],
        ),
    ]
