# Generated by Django 2.2.1 on 2019-06-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='merchantOrUser',
            field=models.BooleanField(default=False),
        ),
    ]
